server:
  port: 8081
info:
  app:
    name: "configserver-microservice"
    description: "SUNUBUS APPLICATION"
    version: "1.0.0"
eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
